##
## Makefile
##
## Made by jules baratoux
## Login   <barato_j@epitech.net>
##
## Started on  Sun May 19 02:33:10 2013 jules baratoux
## Last update Fri Oct 25 17:48:45 2013 lambert kevin
##
## ┌───────────────────────────────────────────────────────────────────────────┐
## │                                MAKEFILE                                   │
## └───────────────────────────────────────────────────────────────────────────┘



NAME	     ?=	libStateManager.a

LD	      =	ar rcs

SRCS	      =	StateManager.cpp


F.C          +=	-W -Wextra -Wall
F.C          +=
F.L          +=
F.I	     += -I./include
F.D	     += -D NDEBUG





all:		start $(NAME)

$(NAME):	compile

clean:		remove_objects

fclean:		clean remove_name

re:		fclean all



























































include .libmake
