NAME	     ?=	defaultIA.so

SRCS =	      	defaultIA.cpp		\

F.C	     +=
F.I	     += -I./include
F.D	     +=

all:		start $(NAME)

$(NAME):	compile

clean:		remove_objects

fclean:		clean remove_name

re:		fclean all

include .libmake
