all:		compile

compile:
		@make --no-print-directory -C ./defaultIA all
		@make --no-print-directory -C ./defaultBoss all

clean:
		@make --no-print-directory -C ./defaultIA clean
		@make --no-print-directory -C ./defaultBoss clean

fclean:
		@make --no-print-directory -C ./defaultIA fclean
		@make --no-print-directory -C ./defaultBoss fclean

re:		fclean all
