## ┌───────────────────────────────────────────────────────────────────────────┐
## │                                MAKEFILE                                   │
## └───────────────────────────────────────────────────────────────────────────┘



NAME	     ?=	libMDynamic.so

SRCS =		DynamicAbstract.cpp


F.C	     +=	-W -Wall -Werror -fPIC
F.I	     +=	-I$(DIR.H)
F.L	     += -shared
F.D	     +=


all:		start $(NAME)

$(NAME):	compile

clean:		remove_objects

fclean:		clean remove_name

re:		fclean all























































include .libmake
